### ISSUE TITLE
Error downloading nerfstudio dataset

### ISSUE THREAD

**Issue by sheshap** [jkulhanek/nerfbaselines#8]
Hi Team,

I faced below error while downloading the nerfstudio dataset. Please help fix it.

Traceback (most recent call last):
  File "/home/ssheshap/anaconda3/bin/nerfbaselines", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ssheshap/anaconda3/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ssheshap/anaconda3/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/ssheshap/anaconda3/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ssheshap/anaconda3/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ssheshap/anaconda3/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ssheshap/anaconda3/lib/python3.11/site-packages/nerfbaselines/cli/__init__.py", line 104, in download_dataset_command
    download_dataset(dataset, output)
  File "/home/ssheshap/anaconda3/lib/python3.11/site-packages/nerfbaselines/datasets/__init__.py", line 22, in download_dataset
    download_fn(path, str(output))
  File "/home/ssheshap/anaconda3/lib/python3.11/site-packages/nerfbaselines/datasets/nerfstudio.py", line 582, in download_nerfstudio_dataset
    download_nerfstudio_dataset(f"nerfstudio/{x}", output / x)
  File "/home/ssheshap/anaconda3/lib/python3.11/site-packages/nerfbaselines/datasets/nerfstudio.py", line 588, in download_nerfstudio_dataset
    download_capture_name(output, capture_url)
  File "/home/ssheshap/anaconda3/lib/python3.11/site-packages/nerfbaselines/datasets/nerfstudio.py", line 546, in download_capture_name
    wget(url, download_path)
  File "/home/ssheshap/anaconda3/lib/python3.11/site-packages/nerfbaselines/io.py", line 44, in wget
    response.raise_for_status()
  File "/home/ssheshap/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/datasets/jkulhanek/nerfbaselines-data/resolve/main/nerfstudio/egypt.zip?download=true

Thanks
Shivanand

**Comment by jkulhanek** [comment]
Hi, thank you for reporting. I fixed the path, it should work now.
